%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'LTV1';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('LTV1.log');
M_.exo_names = 'epsiA';
M_.exo_names_tex = 'epsiA';
M_.exo_names_long = 'epsiA';
M_.exo_names = char(M_.exo_names, 'epsiJ');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiJ');
M_.exo_names_long = char(M_.exo_names_long, 'epsiJ');
M_.exo_names = char(M_.exo_names, 'epsiK');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiK');
M_.exo_names_long = char(M_.exo_names_long, 'epsiK');
M_.exo_names = char(M_.exo_names, 'epsiSe');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiSe');
M_.exo_names_long = char(M_.exo_names_long, 'epsiSe');
M_.exo_names = char(M_.exo_names, 'epsiSm');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiSm');
M_.exo_names_long = char(M_.exo_names_long, 'epsiSm');
M_.exo_names = char(M_.exo_names, 'epsiSB');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiSB');
M_.exo_names_long = char(M_.exo_names_long, 'epsiSB');
M_.exo_names = char(M_.exo_names, 'epsiWb');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiWb');
M_.exo_names_long = char(M_.exo_names_long, 'epsiWb');
M_.exo_names = char(M_.exo_names, 'epsiWe');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiWe');
M_.exo_names_long = char(M_.exo_names_long, 'epsiWe');
M_.exo_names = char(M_.exo_names, 'epsiH');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiH');
M_.exo_names_long = char(M_.exo_names_long, 'epsiH');
M_.exo_names = char(M_.exo_names, 'epsiHd');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiHd');
M_.exo_names_long = char(M_.exo_names_long, 'epsiHd');
M_.exo_names = char(M_.exo_names, 'epsiHk');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiHk');
M_.exo_names_long = char(M_.exo_names_long, 'epsiHk');
M_.exo_names = char(M_.exo_names, 'epsimarkup_m');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsimarkup\_m');
M_.exo_names_long = char(M_.exo_names_long, 'epsimarkup_m');
M_.exo_names = char(M_.exo_names, 'epsimarkup_F');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsimarkup\_F');
M_.exo_names_long = char(M_.exo_names_long, 'epsimarkup_F');
M_.exo_names = char(M_.exo_names, 'epsiEC');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiEC');
M_.exo_names_long = char(M_.exo_names_long, 'epsiEC');
M_.exo_names = char(M_.exo_names, 'epsiECAB');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiECAB');
M_.exo_names_long = char(M_.exo_names_long, 'epsiECAB');
M_.exo_names = char(M_.exo_names, 'epsiEL');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiEL');
M_.exo_names_long = char(M_.exo_names_long, 'epsiEL');
M_.exo_names = char(M_.exo_names, 'epsiEbH');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiEbH');
M_.exo_names_long = char(M_.exo_names_long, 'epsiEbH');
M_.exo_names = char(M_.exo_names, 'epsiEbF');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiEbF');
M_.exo_names_long = char(M_.exo_names_long, 'epsiEbF');
M_.exo_names = char(M_.exo_names, 'epsiLTVH');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiLTVH');
M_.exo_names_long = char(M_.exo_names_long, 'epsiLTVH');
M_.exo_names = char(M_.exo_names, 'epsiLTVF');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsiLTVF');
M_.exo_names_long = char(M_.exo_names_long, 'epsiLTVF');
M_.endo_names = 'b_e';
M_.endo_names_tex = 'B^e_t';
M_.endo_names_long = 'b_e';
M_.endo_names = char(M_.endo_names, 'g_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'g^H_t');
M_.endo_names_long = char(M_.endo_names_long, 'g_H');
M_.endo_names = char(M_.endo_names, 'g_H_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_H\_1');
M_.endo_names_long = char(M_.endo_names_long, 'g_H_1');
M_.endo_names = char(M_.endo_names, 'IH');
M_.endo_names_tex = char(M_.endo_names_tex, 'IH_t');
M_.endo_names_long = char(M_.endo_names_long, 'IH');
M_.endo_names = char(M_.endo_names, 'PH');
M_.endo_names_tex = char(M_.endo_names_tex, 'PH_t');
M_.endo_names_long = char(M_.endo_names_long, 'PH');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, ' A ');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'b_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' b^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'b_m');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, ' C_t ');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'C_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' C^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'C_m');
M_.endo_names = char(M_.endo_names, 'C_s');
M_.endo_names_tex = char(M_.endo_names_tex, ' C^s_t ');
M_.endo_names_long = char(M_.endo_names_long, 'C_s');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, ' D_t ');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'def_rate_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' Def^e_t ');
M_.endo_names_long = char(M_.endo_names_long, 'def_rate_e');
M_.endo_names = char(M_.endo_names, 'def_rate_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' Def^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'def_rate_m');
M_.endo_names = char(M_.endo_names, 'def_rate_B');
M_.endo_names_tex = char(M_.endo_names_tex, ' Def^B_t ');
M_.endo_names_long = char(M_.endo_names_long, 'def_rate_B');
M_.endo_names = char(M_.endo_names, 'epsilonH');
M_.endo_names_tex = char(M_.endo_names_tex, ' \epsilon^H_t ');
M_.endo_names_long = char(M_.endo_names_long, 'epsilonH');
M_.endo_names = char(M_.endo_names, 'epsilonF');
M_.endo_names_tex = char(M_.endo_names_tex, ' \epsilon^F_t ');
M_.endo_names_long = char(M_.endo_names_long, 'epsilonF');
M_.endo_names = char(M_.endo_names, 'G_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' G^e_t ');
M_.endo_names_long = char(M_.endo_names_long, 'G_e');
M_.endo_names = char(M_.endo_names, 'G_e_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_e\_1');
M_.endo_names_long = char(M_.endo_names_long, 'G_e_1');
M_.endo_names = char(M_.endo_names, 'F_pB');
M_.endo_names_tex = char(M_.endo_names_tex, ' F^{pB}_t ');
M_.endo_names_long = char(M_.endo_names_long, 'F_pB');
M_.endo_names = char(M_.endo_names, 'G_B');
M_.endo_names_tex = char(M_.endo_names_tex, ' G^B_t ');
M_.endo_names_long = char(M_.endo_names_long, 'G_B');
M_.endo_names = char(M_.endo_names, 'g_I');
M_.endo_names_tex = char(M_.endo_names_tex, ' g^I_t ');
M_.endo_names_long = char(M_.endo_names_long, 'g_I');
M_.endo_names = char(M_.endo_names, 'g_I_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_I\_1');
M_.endo_names_long = char(M_.endo_names_long, 'g_I_1');
M_.endo_names = char(M_.endo_names, 'G_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' G^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'G_m');
M_.endo_names = char(M_.endo_names, 'G_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'G_m_1');
M_.endo_names = char(M_.endo_names, 'Gamma_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' \Gamma^e_t ');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_e');
M_.endo_names = char(M_.endo_names, 'Gamma_e_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_e\_1');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_e_1');
M_.endo_names = char(M_.endo_names, 'Gamma_B');
M_.endo_names_tex = char(M_.endo_names_tex, ' \Gamma^b_t ');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_B');
M_.endo_names = char(M_.endo_names, 'Gamma_B_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_B\_1');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_B_1');
M_.endo_names = char(M_.endo_names, 'Gamma_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' \Gamma^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_m');
M_.endo_names = char(M_.endo_names, 'Gamma_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma_m_1');
M_.endo_names = char(M_.endo_names, 'F_pi');
M_.endo_names_tex = char(M_.endo_names_tex, ' F^{pi}_t ');
M_.endo_names_long = char(M_.endo_names_long, 'F_pi');
M_.endo_names = char(M_.endo_names, 'F_pe');
M_.endo_names_tex = char(M_.endo_names_tex, ' F^{pe}_t ');
M_.endo_names_long = char(M_.endo_names_long, 'F_pe');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, ' H_t ');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'H_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' H^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'H_m');
M_.endo_names = char(M_.endo_names, 'H_s');
M_.endo_names_tex = char(M_.endo_names_tex, ' H^s_t ');
M_.endo_names_long = char(M_.endo_names_long, 'H_s');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, ' I_t ');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, ' K_t ');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, ' L_t ');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'L_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' L^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'L_m');
M_.endo_names = char(M_.endo_names, 'L_s');
M_.endo_names_tex = char(M_.endo_names_tex, ' L^s_t ');
M_.endo_names_long = char(M_.endo_names_long, 'L_s');
M_.endo_names = char(M_.endo_names, 'Lambda_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' \lambda^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_m');
M_.endo_names = char(M_.endo_names, 'Lambda_s');
M_.endo_names_tex = char(M_.endo_names_tex, ' \lambda^s_t ');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_s');
M_.endo_names = char(M_.endo_names, 'n_b');
M_.endo_names_tex = char(M_.endo_names_tex, ' n^b_t ');
M_.endo_names_long = char(M_.endo_names_long, 'n_b');
M_.endo_names = char(M_.endo_names, 'n_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' n^e_t ');
M_.endo_names_long = char(M_.endo_names_long, 'n_e');
M_.endo_names = char(M_.endo_names, 'omega_bar_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' \bar{\omega^e}_t ');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_e');
M_.endo_names = char(M_.endo_names, 'omega_bar_B');
M_.endo_names_tex = char(M_.endo_names_tex, ' \bar{\omega^B}_t ');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_B');
M_.endo_names = char(M_.endo_names, 'omega_bar_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' \bar{\omega^m}_t ');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_m');
M_.endo_names = char(M_.endo_names, 'PI');
M_.endo_names_tex = char(M_.endo_names_tex, ' \PI     ');
M_.endo_names_long = char(M_.endo_names_long, 'PI');
M_.endo_names = char(M_.endo_names, 'q_H');
M_.endo_names_tex = char(M_.endo_names_tex, ' q^H_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'q_H');
M_.endo_names = char(M_.endo_names, 'q_K');
M_.endo_names_tex = char(M_.endo_names_tex, '  q^K_t ');
M_.endo_names_long = char(M_.endo_names_long, 'q_K');
M_.endo_names = char(M_.endo_names, 'R_D');
M_.endo_names_tex = char(M_.endo_names_tex, '  R^D_t ');
M_.endo_names_long = char(M_.endo_names_long, 'R_D');
M_.endo_names = char(M_.endo_names, 'R_F');
M_.endo_names_tex = char(M_.endo_names_tex, ' R^F_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'R_F');
M_.endo_names = char(M_.endo_names, 'R_H');
M_.endo_names_tex = char(M_.endo_names_tex, '   R^H_t');
M_.endo_names_long = char(M_.endo_names_long, 'R_H');
M_.endo_names = char(M_.endo_names, 'r_K');
M_.endo_names_tex = char(M_.endo_names_tex, ' r^K_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'r_K');
M_.endo_names = char(M_.endo_names, 'R_K');
M_.endo_names_tex = char(M_.endo_names_tex, '  R^K_t ');
M_.endo_names_long = char(M_.endo_names_long, 'R_K');
M_.endo_names = char(M_.endo_names, 'R_m');
M_.endo_names_tex = char(M_.endo_names_tex, '  R^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'R_m');
M_.endo_names = char(M_.endo_names, 'R_tilde_F');
M_.endo_names_tex = char(M_.endo_names_tex, '  \tilde{R}^F_t ');
M_.endo_names_long = char(M_.endo_names_long, 'R_tilde_F');
M_.endo_names = char(M_.endo_names, 'R_tilde_H');
M_.endo_names_tex = char(M_.endo_names_tex, '  \tilde{R}^H_t ');
M_.endo_names_long = char(M_.endo_names_long, 'R_tilde_H');
M_.endo_names = char(M_.endo_names, 'Tr');
M_.endo_names_tex = char(M_.endo_names_tex, ' Tr  ');
M_.endo_names_long = char(M_.endo_names_long, 'Tr');
M_.endo_names = char(M_.endo_names, 'UC_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' UC^m_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'UC_m');
M_.endo_names = char(M_.endo_names, 'UC_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UC\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UC_m_1');
M_.endo_names = char(M_.endo_names, 'UC_s');
M_.endo_names_tex = char(M_.endo_names_tex, ' UC^s_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'UC_s');
M_.endo_names = char(M_.endo_names, 'UC_s_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UC\_s\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UC_s_1');
M_.endo_names = char(M_.endo_names, 'UH_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' UC^h_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'UH_m');
M_.endo_names = char(M_.endo_names, 'UH_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UH\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UH_m_1');
M_.endo_names = char(M_.endo_names, 'UH_s');
M_.endo_names_tex = char(M_.endo_names_tex, '  UH^s_t ');
M_.endo_names_long = char(M_.endo_names_long, 'UH_s');
M_.endo_names = char(M_.endo_names, 'UH_s_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UH\_s\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UH_s_1');
M_.endo_names = char(M_.endo_names, 'UL_m');
M_.endo_names_tex = char(M_.endo_names_tex, '  UK^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'UL_m');
M_.endo_names = char(M_.endo_names, 'UL_m_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UL\_m\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UL_m_1');
M_.endo_names = char(M_.endo_names, 'UL_s');
M_.endo_names_tex = char(M_.endo_names_tex, '  UL^s_t ');
M_.endo_names_long = char(M_.endo_names_long, 'UL_s');
M_.endo_names = char(M_.endo_names, 'UL_s_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'UL\_s\_1');
M_.endo_names_long = char(M_.endo_names_long, 'UL_s_1');
M_.endo_names = char(M_.endo_names, 'Util_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' Util^m_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'Util_m');
M_.endo_names = char(M_.endo_names, 'Util_s');
M_.endo_names_tex = char(M_.endo_names_tex, '  Util^s_t ');
M_.endo_names_long = char(M_.endo_names_long, 'Util_s');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, ' w_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'W_b');
M_.endo_names_tex = char(M_.endo_names_tex, ' W^b_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'W_b');
M_.endo_names = char(M_.endo_names, 'Pr_H');
M_.endo_names_tex = char(M_.endo_names_tex, ' Pr^H_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'Pr_H');
M_.endo_names = char(M_.endo_names, 'W_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' W^e_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'W_e');
M_.endo_names = char(M_.endo_names, 'x_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' X^e_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'x_e');
M_.endo_names = char(M_.endo_names, 'x_m');
M_.endo_names_tex = char(M_.endo_names_tex, ' X^m_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'x_m');
M_.endo_names = char(M_.endo_names, 'xi_e');
M_.endo_names_tex = char(M_.endo_names_tex, ' \xi^e_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'xi_e');
M_.endo_names = char(M_.endo_names, 'xi_m');
M_.endo_names_tex = char(M_.endo_names_tex, '  \xi^m_t ');
M_.endo_names_long = char(M_.endo_names_long, 'xi_m');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, ' Y_t  ');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'Y_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_obs');
M_.endo_names = char(M_.endo_names, 'R_D_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_D\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_D_obs');
M_.endo_names = char(M_.endo_names, 'R_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_m_obs');
M_.endo_names = char(M_.endo_names, 'R_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_H_obs');
M_.endo_names = char(M_.endo_names, 'R_F_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_F\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_F_obs');
M_.endo_names = char(M_.endo_names, 'H_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'H_m_obs');
M_.endo_names = char(M_.endo_names, 'H_s_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_s\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'H_s_obs');
M_.endo_names = char(M_.endo_names, 'b_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'b_m_obs');
M_.endo_names = char(M_.endo_names, 'C_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_obs');
M_.endo_names = char(M_.endo_names, 'C_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_m_obs');
M_.endo_names = char(M_.endo_names, 'C_s_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_s\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_s_obs');
M_.endo_names = char(M_.endo_names, 'D_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'D\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'D_obs');
M_.endo_names = char(M_.endo_names, 'I_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'I\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'I_obs');
M_.endo_names = char(M_.endo_names, 'K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'K_obs');
M_.endo_names = char(M_.endo_names, 'L_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'L_obs');
M_.endo_names = char(M_.endo_names, 'L_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'L_m_obs');
M_.endo_names = char(M_.endo_names, 'L_s_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_s\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'L_s_obs');
M_.endo_names = char(M_.endo_names, 'n_b_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_b\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'n_b_obs');
M_.endo_names = char(M_.endo_names, 'n_e_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_e\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'n_e_obs');
M_.endo_names = char(M_.endo_names, 'q_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'q_H_obs');
M_.endo_names = char(M_.endo_names, 'q_K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'q_K_obs');
M_.endo_names = char(M_.endo_names, 'r_K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_obs');
M_.endo_names = char(M_.endo_names, 'R_K_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_K\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_K_obs');
M_.endo_names = char(M_.endo_names, 'w_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'w_obs');
M_.endo_names = char(M_.endo_names, 'x_e_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_e\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'x_e_obs');
M_.endo_names = char(M_.endo_names, 'x_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'x_m_obs');
M_.endo_names = char(M_.endo_names, 'Vs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Vs');
M_.endo_names_long = char(M_.endo_names_long, 'Vs');
M_.endo_names = char(M_.endo_names, 'Vm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Vm');
M_.endo_names_long = char(M_.endo_names_long, 'Vm');
M_.endo_names = char(M_.endo_names, 'Ve');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ve');
M_.endo_names_long = char(M_.endo_names_long, 'Ve');
M_.endo_names = char(M_.endo_names, 'Vb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Vb');
M_.endo_names_long = char(M_.endo_names_long, 'Vb');
M_.endo_names = char(M_.endo_names, 'EJ');
M_.endo_names_tex = char(M_.endo_names_tex, 'EJ');
M_.endo_names_long = char(M_.endo_names_long, 'EJ');
M_.endo_names = char(M_.endo_names, 'EK');
M_.endo_names_tex = char(M_.endo_names_tex, 'EK');
M_.endo_names_long = char(M_.endo_names_long, 'EK');
M_.endo_names = char(M_.endo_names, 'EH');
M_.endo_names_tex = char(M_.endo_names_tex, 'EH');
M_.endo_names_long = char(M_.endo_names_long, 'EH');
M_.endo_names = char(M_.endo_names, 'ESe');
M_.endo_names_tex = char(M_.endo_names_tex, 'ESe');
M_.endo_names_long = char(M_.endo_names_long, 'ESe');
M_.endo_names = char(M_.endo_names, 'ESm');
M_.endo_names_tex = char(M_.endo_names_tex, 'ESm');
M_.endo_names_long = char(M_.endo_names_long, 'ESm');
M_.endo_names = char(M_.endo_names, 'ESB');
M_.endo_names_tex = char(M_.endo_names_tex, 'ESB');
M_.endo_names_long = char(M_.endo_names_long, 'ESB');
M_.endo_names = char(M_.endo_names, 'EWe');
M_.endo_names_tex = char(M_.endo_names_tex, 'EWe');
M_.endo_names_long = char(M_.endo_names_long, 'EWe');
M_.endo_names = char(M_.endo_names, 'EWb');
M_.endo_names_tex = char(M_.endo_names_tex, 'EWb');
M_.endo_names_long = char(M_.endo_names_long, 'EWb');
M_.endo_names = char(M_.endo_names, 'EdH');
M_.endo_names_tex = char(M_.endo_names_tex, 'EdH');
M_.endo_names_long = char(M_.endo_names_long, 'EdH');
M_.endo_names = char(M_.endo_names, 'EdK');
M_.endo_names_tex = char(M_.endo_names_tex, 'EdK');
M_.endo_names_long = char(M_.endo_names_long, 'EdK');
M_.endo_names = char(M_.endo_names, 'markup_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'markup\_m');
M_.endo_names_long = char(M_.endo_names_long, 'markup_m');
M_.endo_names = char(M_.endo_names, 'markup_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'markup\_F');
M_.endo_names_long = char(M_.endo_names_long, 'markup_F');
M_.endo_names = char(M_.endo_names, 'EC');
M_.endo_names_tex = char(M_.endo_names_tex, 'EC');
M_.endo_names_long = char(M_.endo_names_long, 'EC');
M_.endo_names = char(M_.endo_names, 'ECAB');
M_.endo_names_tex = char(M_.endo_names_tex, 'ECAB');
M_.endo_names_long = char(M_.endo_names_long, 'ECAB');
M_.endo_names = char(M_.endo_names, 'EL');
M_.endo_names_tex = char(M_.endo_names_tex, 'EL');
M_.endo_names_long = char(M_.endo_names_long, 'EL');
M_.endo_names = char(M_.endo_names, 'EbH');
M_.endo_names_tex = char(M_.endo_names_tex, 'EbH');
M_.endo_names_long = char(M_.endo_names_long, 'EbH');
M_.endo_names = char(M_.endo_names, 'EbF');
M_.endo_names_tex = char(M_.endo_names_tex, 'EbF');
M_.endo_names_long = char(M_.endo_names_long, 'EbF');
M_.endo_names = char(M_.endo_names, 'ELTVH');
M_.endo_names_tex = char(M_.endo_names_tex, 'ELTVH');
M_.endo_names_long = char(M_.endo_names_long, 'ELTVH');
M_.endo_names = char(M_.endo_names, 'ELTVF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ELTVF');
M_.endo_names_long = char(M_.endo_names_long, 'ELTVF');
M_.endo_names = char(M_.endo_names, 'phi_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_F');
M_.endo_names_long = char(M_.endo_names_long, 'phi_F');
M_.endo_names = char(M_.endo_names, 'phi_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_H');
M_.endo_names_long = char(M_.endo_names_long, 'phi_H');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'b_e_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_e\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'b_e_obs');
M_.endo_names = char(M_.endo_names, 'bsp_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_F');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_F');
M_.endo_names = char(M_.endo_names, 'bsp_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_H');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_H');
M_.endo_names = char(M_.endo_names, 'Y_net');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net');
M_.endo_names = char(M_.endo_names, 'Y_net_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net_obs');
M_.endo_names = char(M_.endo_names, 'Y_net_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net\_2');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net_2');
M_.endo_names = char(M_.endo_names, 'Y_net_2_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_net\_2\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_net_2_obs');
M_.endo_names = char(M_.endo_names, 'res_chk');
M_.endo_names_tex = char(M_.endo_names_tex, 'res\_chk');
M_.endo_names_long = char(M_.endo_names_long, 'res_chk');
M_.endo_names = char(M_.endo_names, 'deltaH');
M_.endo_names_tex = char(M_.endo_names_tex, 'deltaH');
M_.endo_names_long = char(M_.endo_names_long, 'deltaH');
M_.endo_names = char(M_.endo_names, 'deltaK');
M_.endo_names_tex = char(M_.endo_names_tex, 'deltaK');
M_.endo_names_long = char(M_.endo_names_long, 'deltaK');
M_.endo_names = char(M_.endo_names, 'GDP');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP');
M_.endo_names_long = char(M_.endo_names_long, 'GDP');
M_.endo_names = char(M_.endo_names, 'GDP_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'GDP_obs');
M_.endo_names = char(M_.endo_names, 'H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'H_obs');
M_.endo_names = char(M_.endo_names, 'IH_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'IH\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'IH_obs');
M_.endo_names = char(M_.endo_names, 'res_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'res\_H');
M_.endo_names_long = char(M_.endo_names_long, 'res_H');
M_.endo_names = char(M_.endo_names, 'm_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_e');
M_.endo_names_long = char(M_.endo_names_long, 'm_e');
M_.endo_names = char(M_.endo_names, 'm_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_m');
M_.endo_names_long = char(M_.endo_names_long, 'm_m');
M_.endo_names = char(M_.endo_names, 'av_def');
M_.endo_names_tex = char(M_.endo_names_tex, 'av\_def');
M_.endo_names_long = char(M_.endo_names_long, 'av_def');
M_.endo_names = char(M_.endo_names, 'RDsp');
M_.endo_names_tex = char(M_.endo_names_tex, 'RDsp');
M_.endo_names_long = char(M_.endo_names_long, 'RDsp');
M_.endo_names = char(M_.endo_names, 'R_DD');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_DD');
M_.endo_names_long = char(M_.endo_names_long, 'R_DD');
M_.endo_names = char(M_.endo_names, 'W_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_m');
M_.endo_names_long = char(M_.endo_names_long, 'W_m');
M_.endo_names = char(M_.endo_names, 'W_m_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_m\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'W_m_obs');
M_.endo_names = char(M_.endo_names, 'b_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'b_tot');
M_.endo_names = char(M_.endo_names, 'b_tot_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_tot\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'b_tot_obs');
M_.endo_names = char(M_.endo_names, 'C_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_b');
M_.endo_names_long = char(M_.endo_names_long, 'C_b');
M_.endo_names = char(M_.endo_names, 'C_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_e');
M_.endo_names_long = char(M_.endo_names_long, 'C_e');
M_.endo_names = char(M_.endo_names, 'A1');
M_.endo_names_tex = char(M_.endo_names_tex, 'A1');
M_.endo_names_long = char(M_.endo_names_long, 'A1');
M_.endo_names = char(M_.endo_names, 'B1');
M_.endo_names_tex = char(M_.endo_names_tex, 'B1');
M_.endo_names_long = char(M_.endo_names_long, 'B1');
M_.endo_names = char(M_.endo_names, 'C1');
M_.endo_names_tex = char(M_.endo_names_tex, 'C1');
M_.endo_names_long = char(M_.endo_names_long, 'C1');
M_.endo_names = char(M_.endo_names, 'D1');
M_.endo_names_tex = char(M_.endo_names_tex, 'D1');
M_.endo_names_long = char(M_.endo_names_long, 'D1');
M_.endo_names = char(M_.endo_names, 'R_mi');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_mi');
M_.endo_names_long = char(M_.endo_names_long, 'R_mi');
M_.endo_names = char(M_.endo_names, 'R_Fi');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_Fi');
M_.endo_names_long = char(M_.endo_names_long, 'R_Fi');
M_.endo_names = char(M_.endo_names, 'phib');
M_.endo_names_tex = char(M_.endo_names_tex, 'phib');
M_.endo_names_long = char(M_.endo_names_long, 'phib');
M_.endo_names = char(M_.endo_names, 'roe_B');
M_.endo_names_tex = char(M_.endo_names_tex, 'roe\_B');
M_.endo_names_long = char(M_.endo_names_long, 'roe_B');
M_.endo_names = char(M_.endo_names, 'DY_NET');
M_.endo_names_tex = char(M_.endo_names_tex, 'DY\_NET');
M_.endo_names_long = char(M_.endo_names_long, 'DY_NET');
M_.endo_names = char(M_.endo_names, 'DY_NET_OBS');
M_.endo_names_tex = char(M_.endo_names_tex, 'DY\_NET\_OBS');
M_.endo_names_long = char(M_.endo_names_long, 'DY_NET_OBS');
M_.endo_names = char(M_.endo_names, 'credit_gap_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'credit\_gap\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'credit_gap_obs');
M_.endo_names = char(M_.endo_names, 'bsp_H_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_H\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_H_obs');
M_.endo_names = char(M_.endo_names, 'bsp_F_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsp\_F\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'bsp_F_obs');
M_.endo_names = char(M_.endo_names, 'dy_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dy_data');
M_.endo_names = char(M_.endo_names, 'dq_H_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dq\_H\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dq_H_data');
M_.endo_names = char(M_.endo_names, 'dbe_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dbe\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dbe_data');
M_.endo_names = char(M_.endo_names, 'dbm_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dbm\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dbm_data');
M_.endo_names = char(M_.endo_names, 'db_total_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'db\_total\_data');
M_.endo_names_long = char(M_.endo_names_long, 'db_total_data');
M_.endo_names = char(M_.endo_names, 'bank_rate_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'bank\_rate\_data');
M_.endo_names_long = char(M_.endo_names_long, 'bank_rate_data');
M_.endo_names = char(M_.endo_names, 'b_to_Y_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_to\_Y\_data');
M_.endo_names_long = char(M_.endo_names_long, 'b_to_Y_data');
M_.endo_names = char(M_.endo_names, 'd_b_to_Y_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_b\_to\_Y\_data');
M_.endo_names_long = char(M_.endo_names_long, 'd_b_to_Y_data');
M_.endo_names = char(M_.endo_names, 'int_rate_HH_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'int\_rate\_HH\_data');
M_.endo_names_long = char(M_.endo_names_long, 'int_rate_HH_data');
M_.endo_names = char(M_.endo_names, 'int_rate_business_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'int\_rate\_business\_data');
M_.endo_names_long = char(M_.endo_names_long, 'int_rate_business_data');
M_.endo_names = char(M_.endo_names, 'dw_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dw\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dw_data');
M_.endo_names = char(M_.endo_names, 'dinve_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dinve\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dinve_data');
M_.endo_names = char(M_.endo_names, 'dc_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dc_data');
M_.endo_names = char(M_.endo_names, 'CR_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'CR\_data');
M_.endo_names_long = char(M_.endo_names_long, 'CR_data');
M_.endo_names = char(M_.endo_names, 'welfare_');
M_.endo_names_tex = char(M_.endo_names_tex, 'welfare\_');
M_.endo_names_long = char(M_.endo_names_long, 'welfare_');
M_.endo_names = char(M_.endo_names, 'welfare_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'welfare\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'welfare_obs');
M_.endo_names = char(M_.endo_names, 'dl_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'dl\_data');
M_.endo_names_long = char(M_.endo_names_long, 'dl_data');
M_.endo_names = char(M_.endo_names, 'pb_ratio_data');
M_.endo_names_tex = char(M_.endo_names_tex, 'pb\_ratio\_data');
M_.endo_names_long = char(M_.endo_names_long, 'pb_ratio_data');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_293');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_293');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_293');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_368');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_368');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_368');
M_.endo_partitions = struct();
M_.param_names = 'sigma_epsiHd';
M_.param_names_tex = 'sigma\_epsiHd';
M_.param_names_long = 'sigma_epsiHd';
M_.param_names = char(M_.param_names, 'sigma_epsiHk');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiHk');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiHk');
M_.param_names = char(M_.param_names, 'sigma_epsiA');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiA');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiA');
M_.param_names = char(M_.param_names, 'sigma_epsiJ');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiJ');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiJ');
M_.param_names = char(M_.param_names, 'sigma_epsiK');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiK');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiK');
M_.param_names = char(M_.param_names, 'sigma_epsiH');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiH');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiH');
M_.param_names = char(M_.param_names, 'sigma_epsiSe');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiSe');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiSe');
M_.param_names = char(M_.param_names, 'sigma_epsiSm');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiSm');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiSm');
M_.param_names = char(M_.param_names, 'sigma_epsiSB');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiSB');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiSB');
M_.param_names = char(M_.param_names, 'sigma_epsiWb');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiWb');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiWb');
M_.param_names = char(M_.param_names, 'sigma_epsiRW');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiRW');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiRW');
M_.param_names = char(M_.param_names, 'sigma_epsiWe');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiWe');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiWe');
M_.param_names = char(M_.param_names, 'sigma_epsiEC');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiEC');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiEC');
M_.param_names = char(M_.param_names, 'sigma_epsiEL');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_epsiEL');
M_.param_names_long = char(M_.param_names_long, 'sigma_epsiEL');
M_.param_names = char(M_.param_names, 'pp');
M_.param_names_tex = char(M_.param_names_tex, 'pp');
M_.param_names_long = char(M_.param_names_long, 'pp');
M_.param_names = char(M_.param_names, 'sigma_ELTVH');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ELTVH');
M_.param_names_long = char(M_.param_names_long, 'sigma_ELTVH');
M_.param_names = char(M_.param_names, 'sigma_ELTVF');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ELTVF');
M_.param_names_long = char(M_.param_names_long, 'sigma_ELTVF');
M_.param_names = char(M_.param_names, 'hab');
M_.param_names_tex = char(M_.param_names_tex, 'hab');
M_.param_names_long = char(M_.param_names_long, 'hab');
M_.param_names = char(M_.param_names, 'Cyphi_H');
M_.param_names_tex = char(M_.param_names_tex, 'Cyphi\_H');
M_.param_names_long = char(M_.param_names_long, 'Cyphi_H');
M_.param_names = char(M_.param_names, 'Cyphi_F');
M_.param_names_tex = char(M_.param_names_tex, 'Cyphi\_F');
M_.param_names_long = char(M_.param_names_long, 'Cyphi_F');
M_.param_names = char(M_.param_names, 'phi_Fs');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_Fs');
M_.param_names_long = char(M_.param_names_long, 'phi_Fs');
M_.param_names = char(M_.param_names, 'phi_Hs');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_Hs');
M_.param_names_long = char(M_.param_names_long, 'phi_Hs');
M_.param_names = char(M_.param_names, 'alphaa');
M_.param_names_tex = char(M_.param_names_tex, 'alphaa');
M_.param_names_long = char(M_.param_names_long, 'alphaa');
M_.param_names = char(M_.param_names, 'delta_K');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_K');
M_.param_names_long = char(M_.param_names_long, 'delta_K');
M_.param_names = char(M_.param_names, 'delta_H');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_H');
M_.param_names_long = char(M_.param_names_long, 'delta_H');
M_.param_names = char(M_.param_names, 'betta_m');
M_.param_names_tex = char(M_.param_names_tex, 'betta\_m');
M_.param_names_long = char(M_.param_names_long, 'betta_m');
M_.param_names = char(M_.param_names, 'betta_s');
M_.param_names_tex = char(M_.param_names_tex, 'betta\_s');
M_.param_names_long = char(M_.param_names_long, 'betta_s');
M_.param_names = char(M_.param_names, 'mu_m');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_m');
M_.param_names_long = char(M_.param_names_long, 'mu_m');
M_.param_names = char(M_.param_names, 'mu_e');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_e');
M_.param_names_long = char(M_.param_names_long, 'mu_e');
M_.param_names = char(M_.param_names, 'mu_B');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_B');
M_.param_names_long = char(M_.param_names_long, 'mu_B');
M_.param_names = char(M_.param_names, 'sigma_e1');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_e1');
M_.param_names_long = char(M_.param_names_long, 'sigma_e1');
M_.param_names = char(M_.param_names, 'sigma_m1');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_m1');
M_.param_names_long = char(M_.param_names_long, 'sigma_m1');
M_.param_names = char(M_.param_names, 'sigma_B');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_B');
M_.param_names_long = char(M_.param_names_long, 'sigma_B');
M_.param_names = char(M_.param_names, 'varphi_s');
M_.param_names_tex = char(M_.param_names_tex, 'varphi\_s');
M_.param_names_long = char(M_.param_names_long, 'varphi_s');
M_.param_names = char(M_.param_names, 'varphi_m');
M_.param_names_tex = char(M_.param_names_tex, 'varphi\_m');
M_.param_names_long = char(M_.param_names_long, 'varphi_m');
M_.param_names = char(M_.param_names, 'v_s');
M_.param_names_tex = char(M_.param_names_tex, 'v\_s');
M_.param_names_long = char(M_.param_names_long, 'v_s');
M_.param_names = char(M_.param_names, 'v_m');
M_.param_names_tex = char(M_.param_names_tex, 'v\_m');
M_.param_names_long = char(M_.param_names_long, 'v_m');
M_.param_names = char(M_.param_names, 'chi_b');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_b');
M_.param_names_long = char(M_.param_names_long, 'chi_b');
M_.param_names = char(M_.param_names, 'chi_e');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_e');
M_.param_names_long = char(M_.param_names_long, 'chi_e');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'a_e');
M_.param_names_tex = char(M_.param_names_tex, 'a\_e');
M_.param_names_long = char(M_.param_names_long, 'a_e');
M_.param_names = char(M_.param_names, 'a_s');
M_.param_names_tex = char(M_.param_names_tex, 'a\_s');
M_.param_names_long = char(M_.param_names_long, 'a_s');
M_.param_names = char(M_.param_names, 'a_b');
M_.param_names_tex = char(M_.param_names_tex, 'a\_b');
M_.param_names_long = char(M_.param_names_long, 'a_b');
M_.param_names = char(M_.param_names, 'psi_i');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_i');
M_.param_names_long = char(M_.param_names_long, 'psi_i');
M_.param_names = char(M_.param_names, 'psi_h');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_h');
M_.param_names_long = char(M_.param_names_long, 'psi_h');
M_.param_names = char(M_.param_names, 'rhoA');
M_.param_names_tex = char(M_.param_names_tex, 'rhoA');
M_.param_names_long = char(M_.param_names_long, 'rhoA');
M_.param_names = char(M_.param_names, 'rhoJ');
M_.param_names_tex = char(M_.param_names_tex, 'rhoJ');
M_.param_names_long = char(M_.param_names_long, 'rhoJ');
M_.param_names = char(M_.param_names, 'rhoK');
M_.param_names_tex = char(M_.param_names_tex, 'rhoK');
M_.param_names_long = char(M_.param_names_long, 'rhoK');
M_.param_names = char(M_.param_names, 'rhoH');
M_.param_names_tex = char(M_.param_names_tex, 'rhoH');
M_.param_names_long = char(M_.param_names_long, 'rhoH');
M_.param_names = char(M_.param_names, 'rhoSe');
M_.param_names_tex = char(M_.param_names_tex, 'rhoSe');
M_.param_names_long = char(M_.param_names_long, 'rhoSe');
M_.param_names = char(M_.param_names, 'rhoSm');
M_.param_names_tex = char(M_.param_names_tex, 'rhoSm');
M_.param_names_long = char(M_.param_names_long, 'rhoSm');
M_.param_names = char(M_.param_names, 'rhoSB');
M_.param_names_tex = char(M_.param_names_tex, 'rhoSB');
M_.param_names_long = char(M_.param_names_long, 'rhoSB');
M_.param_names = char(M_.param_names, 'rhoWb');
M_.param_names_tex = char(M_.param_names_tex, 'rhoWb');
M_.param_names_long = char(M_.param_names_long, 'rhoWb');
M_.param_names = char(M_.param_names, 'rhoWe');
M_.param_names_tex = char(M_.param_names_tex, 'rhoWe');
M_.param_names_long = char(M_.param_names_long, 'rhoWe');
M_.param_names = char(M_.param_names, 'rhoHd');
M_.param_names_tex = char(M_.param_names_tex, 'rhoHd');
M_.param_names_long = char(M_.param_names_long, 'rhoHd');
M_.param_names = char(M_.param_names, 'rhoHk');
M_.param_names_tex = char(M_.param_names_tex, 'rhoHk');
M_.param_names_long = char(M_.param_names_long, 'rhoHk');
M_.param_names = char(M_.param_names, 'rhoRW');
M_.param_names_tex = char(M_.param_names_tex, 'rhoRW');
M_.param_names_long = char(M_.param_names_long, 'rhoRW');
M_.param_names = char(M_.param_names, 'rho_markup_m');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_markup\_m');
M_.param_names_long = char(M_.param_names_long, 'rho_markup_m');
M_.param_names = char(M_.param_names, 'rho_markup_F');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_markup\_F');
M_.param_names_long = char(M_.param_names_long, 'rho_markup_F');
M_.param_names = char(M_.param_names, 'rhoEC');
M_.param_names_tex = char(M_.param_names_tex, 'rhoEC');
M_.param_names_long = char(M_.param_names_long, 'rhoEC');
M_.param_names = char(M_.param_names, 'rhoECAB');
M_.param_names_tex = char(M_.param_names_tex, 'rhoECAB');
M_.param_names_long = char(M_.param_names_long, 'rhoECAB');
M_.param_names = char(M_.param_names, 'rhoEL');
M_.param_names_tex = char(M_.param_names_tex, 'rhoEL');
M_.param_names_long = char(M_.param_names_long, 'rhoEL');
M_.param_names = char(M_.param_names, 'rhoEbH');
M_.param_names_tex = char(M_.param_names_tex, 'rhoEbH');
M_.param_names_long = char(M_.param_names_long, 'rhoEbH');
M_.param_names = char(M_.param_names, 'rhoEbF');
M_.param_names_tex = char(M_.param_names_tex, 'rhoEbF');
M_.param_names_long = char(M_.param_names_long, 'rhoEbF');
M_.param_names = char(M_.param_names, 'rhoLTVH');
M_.param_names_tex = char(M_.param_names_tex, 'rhoLTVH');
M_.param_names_long = char(M_.param_names_long, 'rhoLTVH');
M_.param_names = char(M_.param_names, 'rhoLTVF');
M_.param_names_tex = char(M_.param_names_tex, 'rhoLTVF');
M_.param_names_long = char(M_.param_names_long, 'rhoLTVF');
M_.param_names = char(M_.param_names, 'zeta_m');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_m');
M_.param_names_long = char(M_.param_names_long, 'zeta_m');
M_.param_names = char(M_.param_names, 'zeta_F');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_F');
M_.param_names_long = char(M_.param_names_long, 'zeta_F');
M_.param_names = char(M_.param_names, 'epsilonH1s');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonH1s');
M_.param_names_long = char(M_.param_names_long, 'epsilonH1s');
M_.param_names = char(M_.param_names, 'epsilonF1s');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonF1s');
M_.param_names_long = char(M_.param_names_long, 'epsilonF1s');
M_.param_names = char(M_.param_names, 'tau_H');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_H');
M_.param_names_long = char(M_.param_names_long, 'tau_H');
M_.param_names = char(M_.param_names, 'tau_F');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_F');
M_.param_names_long = char(M_.param_names_long, 'tau_F');
M_.param_names = char(M_.param_names, 'rp');
M_.param_names_tex = char(M_.param_names_tex, 'rp');
M_.param_names_long = char(M_.param_names_long, 'rp');
M_.param_names = char(M_.param_names, 'rpe');
M_.param_names_tex = char(M_.param_names_tex, 'rpe');
M_.param_names_long = char(M_.param_names_long, 'rpe');
M_.param_names = char(M_.param_names, 'phiinf1');
M_.param_names_tex = char(M_.param_names_tex, 'phiinf1');
M_.param_names_long = char(M_.param_names_long, 'phiinf1');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'psib');
M_.param_names_tex = char(M_.param_names_tex, 'psib');
M_.param_names_long = char(M_.param_names_long, 'psib');
M_.param_names = char(M_.param_names, 'phis');
M_.param_names_tex = char(M_.param_names_tex, 'phis');
M_.param_names_long = char(M_.param_names_long, 'phis');
M_.param_names = char(M_.param_names, 'LTVHrule');
M_.param_names_tex = char(M_.param_names_tex, 'LTVHrule');
M_.param_names_long = char(M_.param_names_long, 'LTVHrule');
M_.param_names = char(M_.param_names, 'LTVFrule');
M_.param_names_tex = char(M_.param_names_tex, 'LTVFrule');
M_.param_names_long = char(M_.param_names_long, 'LTVFrule');
M_.param_names = char(M_.param_names, 'gamma_y');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_y');
M_.param_names_long = char(M_.param_names_long, 'gamma_y');
M_.param_names = char(M_.param_names, 'gamma_w');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_w');
M_.param_names_long = char(M_.param_names_long, 'gamma_w');
M_.param_names = char(M_.param_names, 'gamma_inve');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_inve');
M_.param_names_long = char(M_.param_names_long, 'gamma_inve');
M_.param_names = char(M_.param_names, 'gamma_c');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_c');
M_.param_names_long = char(M_.param_names_long, 'gamma_c');
M_.param_names = char(M_.param_names, 'gamma_dbe');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_dbe');
M_.param_names_long = char(M_.param_names_long, 'gamma_dbe');
M_.param_names = char(M_.param_names, 'gamma_dbm');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_dbm');
M_.param_names_long = char(M_.param_names_long, 'gamma_dbm');
M_.param_names = char(M_.param_names, 'gamma_bspH');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_bspH');
M_.param_names_long = char(M_.param_names_long, 'gamma_bspH');
M_.param_names = char(M_.param_names, 'gamma_dq_H');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_dq\_H');
M_.param_names_long = char(M_.param_names_long, 'gamma_dq_H');
M_.param_names = char(M_.param_names, 'def_rate_ss');
M_.param_names_tex = char(M_.param_names_tex, 'def\_rate\_ss');
M_.param_names_long = char(M_.param_names_long, 'def_rate_ss');
M_.param_names = char(M_.param_names, 'omikronH');
M_.param_names_tex = char(M_.param_names_tex, 'omikronH');
M_.param_names_long = char(M_.param_names_long, 'omikronH');
M_.param_names = char(M_.param_names, 'omikronF');
M_.param_names_tex = char(M_.param_names_tex, 'omikronF');
M_.param_names_long = char(M_.param_names_long, 'omikronF');
M_.param_names = char(M_.param_names, 'pb_mean');
M_.param_names_tex = char(M_.param_names_tex, 'pb\_mean');
M_.param_names_long = char(M_.param_names_long, 'pb_mean');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 20;
M_.endo_nbr = 193;
M_.param_nbr = 93;
M_.orig_endo_nbr = 191;
M_.aux_vars(1).endo_index = 192;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 193;
M_.aux_vars(2).type = 0;
options_.varobs = cell(1);
options_.varobs(1)  = {'dy_data'};
options_.varobs(2)  = {'dw_data'};
options_.varobs(3)  = {'dc_data'};
options_.varobs(4)  = {'dinve_data'};
options_.varobs(5)  = {'int_rate_HH_data'};
options_.varobs(6)  = {'int_rate_business_data'};
options_.varobs(7)  = {'bank_rate_data'};
options_.varobs(8)  = {'dq_H_data'};
options_.varobs(9)  = {'dbm_data'};
options_.varobs(10)  = {'dbe_data'};
options_.varobs_id = [ 174 184 186 185 182 183 179 175 177 176  ];
M_.Sigma_e = zeros(20, 20);
M_.Correlation_matrix = eye(20, 20);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('LTV1_static');
erase_compiled_function('LTV1_dynamic');
M_.orig_eq_nbr = 191;
M_.eq_nbr = 193;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 56 0;
 0 57 0;
 0 58 249;
 2 59 250;
 0 60 0;
 3 61 0;
 4 62 0;
 0 63 0;
 5 64 0;
 6 65 0;
 7 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 8 70 0;
 9 71 0;
 0 72 251;
 0 73 0;
 0 74 252;
 0 75 253;
 0 76 0;
 0 77 254;
 0 78 255;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 256;
 0 87 257;
 10 88 0;
 11 89 0;
 12 90 0;
 13 91 258;
 14 92 0;
 15 93 0;
 0 94 0;
 0 95 0;
 0 96 259;
 0 97 260;
 0 98 0;
 16 99 0;
 0 100 261;
 0 101 0;
 0 102 262;
 0 103 0;
 17 104 263;
 18 105 264;
 19 106 0;
 20 107 0;
 0 108 265;
 0 109 0;
 0 110 266;
 21 111 267;
 0 112 268;
 0 113 269;
 0 114 0;
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 270;
 0 121 0;
 0 122 271;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 272;
 0 132 0;
 22 133 0;
 23 134 0;
 0 135 0;
 0 136 273;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 0;
 24 145 0;
 25 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 26 150 0;
 0 151 0;
 0 152 0;
 0 153 0;
 0 154 0;
 0 155 0;
 0 156 0;
 27 157 0;
 0 158 0;
 0 159 0;
 0 160 0;
 28 161 0;
 0 162 0;
 0 163 0;
 0 164 274;
 0 165 275;
 0 166 0;
 0 167 0;
 29 168 0;
 30 169 0;
 31 170 0;
 32 171 0;
 33 172 0;
 34 173 0;
 35 174 0;
 36 175 0;
 37 176 0;
 38 177 0;
 39 178 0;
 40 179 0;
 41 180 0;
 42 181 0;
 43 182 0;
 44 183 0;
 45 184 0;
 46 185 0;
 47 186 0;
 0 187 0;
 0 188 0;
 0 189 0;
 48 190 0;
 0 191 0;
 0 192 0;
 49 193 0;
 50 194 0;
 0 195 0;
 0 196 0;
 0 197 0;
 0 198 276;
 51 199 0;
 0 200 0;
 0 201 0;
 0 202 0;
 52 203 0;
 0 204 0;
 0 205 0;
 0 206 0;
 0 207 0;
 0 208 0;
 0 209 277;
 0 210 0;
 0 211 0;
 0 212 0;
 0 213 0;
 0 214 0;
 0 215 0;
 0 216 278;
 0 217 279;
 0 218 280;
 0 219 281;
 0 220 0;
 0 221 0;
 0 222 0;
 0 223 0;
 0 224 0;
 0 225 0;
 53 226 0;
 0 227 0;
 0 228 0;
 0 229 0;
 0 230 0;
 0 231 0;
 0 232 0;
 0 233 0;
 0 234 0;
 54 235 0;
 0 236 0;
 0 237 0;
 0 238 0;
 0 239 0;
 0 240 0;
 0 241 0;
 0 242 0;
 0 243 0;
 0 244 0;
 0 245 0;
 55 246 0;
 0 247 282;
 0 248 283;]';
M_.nstatic = 108;
M_.nfwrd   = 30;
M_.npred   = 50;
M_.nboth   = 5;
M_.nsfwrd   = 35;
M_.nspred   = 55;
M_.ndynamic   = 85;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:20];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(193, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(20, 1);
M_.params = NaN(93, 1);
M_.NNZDerivatives = [772; -1; -1];
load LTV1_parameter_values.mat;
M_.params( 1 ) = set_sigma_epsiHd;
sigma_epsiHd = M_.params( 1 );
M_.params( 2 ) = set_sigma_epsiHk;
sigma_epsiHk = M_.params( 2 );
M_.params( 3 ) = set_sigma_epsiA;
sigma_epsiA = M_.params( 3 );
M_.params( 4 ) = set_sigma_epsiJ;
sigma_epsiJ = M_.params( 4 );
M_.params( 5 ) = set_sigma_epsiK;
sigma_epsiK = M_.params( 5 );
M_.params( 6 ) = set_sigma_epsiH;
sigma_epsiH = M_.params( 6 );
M_.params( 7 ) = set_sigma_epsiSe;
sigma_epsiSe = M_.params( 7 );
M_.params( 8 ) = set_sigma_epsiSm;
sigma_epsiSm = M_.params( 8 );
sigma_epsimarkup_m=set_sigma_epsimarkup_m;
sigma_epsimarkup_F=set_sigma_epsimarkup_F;
M_.params( 9 ) = set_sigma_epsiSB;
sigma_epsiSB = M_.params( 9 );
M_.params( 10 ) = set_sigma_epsiWb;
sigma_epsiWb = M_.params( 10 );
M_.params( 11 ) = set_sigma_epsiRW;
sigma_epsiRW = M_.params( 11 );
M_.params( 12 ) = set_sigma_epsiWe;
sigma_epsiWe = M_.params( 12 );
M_.params( 13 ) = set_sigma_epsiEC;
sigma_epsiEC = M_.params( 13 );
sigma_epsiECAB=set_sigma_epsiECAB;
M_.params( 14 ) = set_sigma_epsiEL;
sigma_epsiEL = M_.params( 14 );
sigma_epsiEbH=set_sigma_epsiEbH;
sigma_epsiEbF=set_sigma_epsiEbF;
M_.params( 16 ) = set_sigma_ELTVH;
sigma_ELTVH = M_.params( 16 );
M_.params( 17 ) = set_sigma_ELTVF;
sigma_ELTVF = M_.params( 17 );
M_.params( 15 ) = set_pp;
pp = M_.params( 15 );
M_.params( 27 ) = set_betta_s;
betta_s = M_.params( 27 );
M_.params( 26 ) = set_betta_m;
betta_m = M_.params( 26 );
M_.params( 18 ) = set_hab;
hab = M_.params( 18 );
M_.params( 19 ) = set_Cyphi_H;
Cyphi_H = M_.params( 19 );
M_.params( 22 ) = set_phi_Hs;
phi_Hs = M_.params( 22 );
M_.params( 20 ) = set_Cyphi_F;
Cyphi_F = M_.params( 20 );
M_.params( 21 ) = set_phi_Fs;
phi_Fs = M_.params( 21 );
M_.params( 23 ) = set_alphaa;
alphaa = M_.params( 23 );
M_.params( 73 ) = set_rp;
rp = M_.params( 73 );
M_.params( 74 ) = set_rpe;
rpe = M_.params( 74 );
M_.params( 24 ) = set_delta_K;
delta_K = M_.params( 24 );
M_.params( 25 ) = set_delta_H;
delta_H = M_.params( 25 );
M_.params( 28 ) = set_mu_m;
mu_m = M_.params( 28 );
M_.params( 29 ) = set_mu_e;
mu_e = M_.params( 29 );
M_.params( 30 ) = set_mu_B;
mu_B = M_.params( 30 );
M_.params( 31 ) = set_sigma_e1;
sigma_e1 = M_.params( 31 );
M_.params( 32 ) = set_sigma_m1;
sigma_m1 = M_.params( 32 );
M_.params( 33 ) = set_sigma_B;
sigma_B = M_.params( 33 );
M_.params( 34 ) = set_varphi_s;
varphi_s = M_.params( 34 );
M_.params( 35 ) = set_varphi_m;
varphi_m = M_.params( 35 );
M_.params( 36 ) = set_v_s;
v_s = M_.params( 36 );
M_.params( 37 ) = set_v_m;
v_m = M_.params( 37 );
M_.params( 38 ) = set_chi_b;
chi_b = M_.params( 38 );
M_.params( 39 ) = set_chi_e;
chi_e = M_.params( 39 );
M_.params( 40 ) = set_eta;
eta = M_.params( 40 );
M_.params( 41 ) = set_a_e;
a_e = M_.params( 41 );
M_.params( 42 ) = set_a_s;
a_s = M_.params( 42 );
M_.params( 43 ) = set_a_b;
a_b = M_.params( 43 );
M_.params( 44 ) = set_psi_i;
psi_i = M_.params( 44 );
M_.params( 45 ) = set_psi_h;
psi_h = M_.params( 45 );
M_.params( 46 ) = set_rhoA;
rhoA = M_.params( 46 );
M_.params( 47 ) = set_rhoJ;
rhoJ = M_.params( 47 );
M_.params( 48 ) = set_rhoK;
rhoK = M_.params( 48 );
M_.params( 50 ) = set_rhoSe;
rhoSe = M_.params( 50 );
M_.params( 51 ) = set_rhoSm;
rhoSm = M_.params( 51 );
M_.params( 52 ) = set_rhoSB;
rhoSB = M_.params( 52 );
M_.params( 53 ) = set_rhoWb;
rhoWb = M_.params( 53 );
M_.params( 54 ) = set_rhoWe;
rhoWe = M_.params( 54 );
M_.params( 55 ) = set_rhoHd;
rhoHd = M_.params( 55 );
M_.params( 49 ) = set_rhoH;
rhoH = M_.params( 49 );
M_.params( 56 ) = set_rhoHk;
rhoHk = M_.params( 56 );
M_.params( 58 ) = set_rho_markup_m;
rho_markup_m = M_.params( 58 );
M_.params( 59 ) = set_rho_markup_F;
rho_markup_F = M_.params( 59 );
M_.params( 60 ) = set_rhoEC;
rhoEC = M_.params( 60 );
M_.params( 61 ) = set_rhoECAB;
rhoECAB = M_.params( 61 );
M_.params( 62 ) = set_rhoEL;
rhoEL = M_.params( 62 );
M_.params( 63 ) = set_rhoEbH;
rhoEbH = M_.params( 63 );
M_.params( 64 ) = set_rhoEbF;
rhoEbF = M_.params( 64 );
M_.params( 65 ) = set_rhoLTVH;
rhoLTVH = M_.params( 65 );
M_.params( 66 ) = set_rhoLTVF;
rhoLTVF = M_.params( 66 );
M_.params( 57 ) = set_rhoRW;
rhoRW = M_.params( 57 );
M_.params( 67 ) = set_zeta_m;
zeta_m = M_.params( 67 );
M_.params( 68 ) = set_zeta_F;
zeta_F = M_.params( 68 );
M_.params( 69 ) = set_epsilonH1s;
epsilonH1s = M_.params( 69 );
M_.params( 70 ) = set_epsilonF1s;
epsilonF1s = M_.params( 70 );
M_.params( 71 ) = set_tau_H;
tau_H = M_.params( 71 );
M_.params( 72 ) = set_tau_F;
tau_F = M_.params( 72 );
M_.params( 75 ) = set_phiinf1;
phiinf1 = M_.params( 75 );
M_.params( 76 ) = set_kappa;
kappa = M_.params( 76 );
M_.params( 77 ) = set_nu;
nu = M_.params( 77 );
M_.params( 78 ) = set_psib;
psib = M_.params( 78 );
M_.params( 79 ) = set_phis;
phis = M_.params( 79 );
M_.params( 80 ) = set_LTVHrule;
LTVHrule = M_.params( 80 );
M_.params( 81 ) = set_LTVFrule;
LTVFrule = M_.params( 81 );
M_.params( 82 ) = set_gamma_y;
gamma_y = M_.params( 82 );
M_.params( 83 ) = set_gamma_w;
gamma_w = M_.params( 83 );
M_.params( 84 ) = set_gamma_inve;
gamma_inve = M_.params( 84 );
M_.params( 85 ) = set_gamma_c;
gamma_c = M_.params( 85 );
M_.params( 86 ) = set_gamma_dbe;
gamma_dbe = M_.params( 86 );
M_.params( 87 ) = set_gamma_dbm;
gamma_dbm = M_.params( 87 );
M_.params( 88 ) = set_gamma_bspH;
gamma_bspH = M_.params( 88 );
M_.params( 89 ) = set_gamma_dq_H;
gamma_dq_H = M_.params( 89 );
M_.params( 90 ) = set_def_rate_ss;
def_rate_ss = M_.params( 90 );
M_.params( 91 ) = set_omikronH;
omikronH = M_.params( 91 );
M_.params( 92 ) = set_omikronF;
omikronF = M_.params( 92 );
M_.params( 93 ) = set_pb_mean;
pb_mean = M_.params( 93 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(3);
M_.Sigma_e(2, 2) = M_.params(4);
M_.Sigma_e(3, 3) = M_.params(5);
M_.Sigma_e(4, 4) = M_.params(7);
M_.Sigma_e(5, 5) = M_.params(8);
M_.Sigma_e(6, 6) = M_.params(9);
M_.Sigma_e(7, 7) = M_.params(10);
M_.Sigma_e(8, 8) = M_.params(12);
M_.Sigma_e(9, 9) = M_.params(6);
M_.Sigma_e(10, 10) = M_.params(1);
M_.Sigma_e(11, 11) = M_.params(2);
M_.Sigma_e(12, 12) = sigma_epsimarkup_m;
M_.Sigma_e(13, 13) = sigma_epsimarkup_F;
M_.Sigma_e(14, 14) = M_.params(13);
M_.Sigma_e(15, 15) = sigma_epsiECAB;
M_.Sigma_e(16, 16) = M_.params(14);
M_.Sigma_e(17, 17) = sigma_epsiEbH;
M_.Sigma_e(18, 18) = sigma_epsiEbF;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 44, 8.4488, 1, 100, 3, 5, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, 10.2520, 1, 100, 3, 5, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.1, 0, 99, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.1, 0, 99, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 14, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 15, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 19, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 18, 0.1, 0, 99, 5, 10, 5.773502691896258, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 46, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 49, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 52, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 54, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 58, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 59, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 60, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 61, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 64, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 65, 0.01, 0, 1, 1, 0.5, 0.2, NaN, NaN, NaN ];
options_.cova_compute = 0;
options_.diffuse_kalman_tol = 1e-15;
options_.kalman_algo = 4;
options_.mh_drop = 0.5;
options_.mh_jscale = 0.2;
options_.mh_nblck = 1;
options_.mh_replic = 0000;
options_.mode_compute = 0;
options_.nodiagnostic = 1;
options_.nograph = 1;
options_.presample = 8;
options_.datafile = 'estimation_dataset_quarterly.mat';
options_.mode_file = 'LTV1_mode.mat';
options_.optim_opt = '''TolFun'',1e-7,''TolX'',1e-7,''Display'',''iter'',''MaxIter'',500,''Hessian'',''bfgs''';
options_.first_obs = 3;
options_.nobs = 72;
options_.order = 1;
var_list_ = char();
oo_recursive_=dynare_estimation(var_list_);
M_.shock_groups.default.group1.label = 'Productivity';
M_.shock_groups.default.group1.shocks = { 'epsiA'};
M_.shock_groups.default.group2.label = 'Housing Preference';
M_.shock_groups.default.group2.shocks = { 'epsiJ'};
M_.shock_groups.default.group3.label = 'House Price Shock';
M_.shock_groups.default.group3.shocks = { 'epsiH'};
M_.shock_groups.default.group4.label = 'Business Risk';
M_.shock_groups.default.group4.shocks = { 'epsiSe'};
M_.shock_groups.default.group5.label = 'Bank Risk';
M_.shock_groups.default.group5.shocks = { 'epsiSB'};
M_.shock_groups.default.group6.label = 'Entrepreneur Net Worth';
M_.shock_groups.default.group6.shocks = { 'epsiWe'};
M_.shock_groups.default.group7.label = 'Mortgage Lending Mark-up';
M_.shock_groups.default.group7.shocks = { 'epsimarkup_m'};
M_.shock_groups.default.group8.label = 'Corporate Lending Mark-up';
M_.shock_groups.default.group8.shocks = { 'epsimarkup_F'};
M_.shock_groups.default.group9.label = 'Consumption Preference';
M_.shock_groups.default.group9.shocks = { 'epsiEC'};
M_.shock_groups.default.group10.label = 'Bank Capital';
M_.shock_groups.default.group10.shocks = { 'epsiECAB'};
M_.shock_groups.default.group11.label = 'Expected Capital Price';
M_.shock_groups.default.group11.shocks = { 'epsiEbF'};
M_.shock_groups.default.group12.label = 'Household LTV';
M_.shock_groups.default.group12.shocks = { 'epsiLTVH'};
options_.irf = 40;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
options_.shock_decomp.init_state = 1;
options_.datafile = 'estimation_dataset_quarterly.mat';
options_.parameter_set = 'posterior_mode';
options_.plot_shock_decomp.use_shock_groups = 'default';
var_list_ = char('dy_data','dq_H_data','int_rate_HH_data','int_rate_business_data','bank_rate_data','dbe_data','dbm_data','dinve_data','dw_data','dc_data','pb_ratio_data');
[oo_,M_]= shock_decomposition(M_,oo_,options_,var_list_,bayestopt_,estim_params_);
save('LTV1_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('LTV1_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('LTV1_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('LTV1_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('LTV1_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('LTV1_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('LTV1_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
