function endo_name =switch_endo_name(endo_name2)


names_short={'dy_data' ...
                 'dw_data'...
                    'dc_data'...
                       'dinve_data'...
                      'int_rate_HH_2yearLTV75'...
                      'int_rate_business_data'...
                      'bank_rate_data'...
                      'dq_H_data'...
                      'dbm_data'};



% endo_name=endo_name2;
% endo_name.String=names_short;
%                   
end